FitnessWeb/FitnessWeb/Controllers/DanisanPanelController.cs
using FitnessWeb.Models.Siniflar;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Net.Security;
using System.Security.Cryptography.X509Certificates;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Security;

namespace FitnessWeb.Controllers
{
    public class DanisanPanelController : Controller
    {
        // GET: DanisanPanel
        Context c = new Context();
        [Authorize]
        public ActionResult Index()
        {
            var mail = (string)Session["DabisanMailAdresi"];
            var degerler = c.Danisanlars.FirstOrDefault(x => x.DabisanMailAdresi == mail);
            ViewBag.m = mail;
            return View(degerler);
        }
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();
            return RedirectToAction("Index", "Login");
        }
        public ActionResult DanisanBilgiGüncelle(Danisanlar d)
        {

           
            var danisan = c.Danisanlars.Find(d.DanisanId);
            danisan.Cinsiyet = d.Cinsiyet;
            danisan.DanisanIsım = d.DanisanIsım;
            danisan.DanisanSifre = d.DanisanSifre;
            danisan.DabisanMailAdresi = d.DabisanMailAdresi;
            danisan.TelefonNo = d.TelefonNo;
            danisan.DogumTarih = d.DogumTarih;
          
            c.SaveChanges();
            return RedirectToAction("Index");

        }
        [HttpGet]
        public ActionResult SifreReset()
        {
            return View();
                 
        }
            [HttpPost]
        public ActionResult SifreReset(Danisanlar d)
        {
            var model = c.Danisanlars.Where(x => x.DabisanMailAdresi == d.DabisanMailAdresi).FirstOrDefault();
            if(model!=null)
            {
                SmtpClient smtpClient = new SmtpClient("smtp.outlook.com", 587);
                smtpClient.UseDefaultCredentials = false;
                smtpClient.Credentials = new System.Net.NetworkCredential("muratakay123456@outlook.com", "Akay123456");
                smtpClient.DeliveryMethod = SmtpDeliveryMethod.Network;
                smtpClient.EnableSsl = true;

                MailMessage mail = new MailMessage();

                mail.From = new MailAddress("muratakay123456@outlook.com", "User");
                mail.To.Add(new MailAddress(model.DabisanMailAdresi));
                ServicePointManager.ServerCertificateValidationCallback = delegate (object s, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors) { return true; };
                smtpClient.Send(mail);

            }

          
            else
            {
                ViewBag.uyari = "hata oluştu tekrar deneyiniz";

               
            }
            return View();
        }

        public ActionResult Kategoriler()
        {
            var deger = c.Kategoris.Where(x=> x.durum == true).ToList();
            return View(deger);
        }

        public ActionResult kategori1(int id)
        {
            var deger = c.Antrenörs.Where(x => x.kategoriId == id).ToList();
            var deger2 = c.Antrenörs.Select(x => x.AntMailAdresi).FirstOrDefault();
            ViewBag.ma = deger2;
            return View(deger);

        }
        public ActionResult degerler()
        {
            var mail = (string)Session["DabisanMailAdresi"];
            var degerler = c.Danisanlars.FirstOrDefault(x => x.DabisanMailAdresi == mail);
            ViewBag.m = mail;
            return View(degerler);

        }

        public ActionResult degergüncelle(Danisanlar d)
        {


            var danisan = c.Danisanlars.Find(d.DanisanId);
            danisan.boy = d.boy;
            danisan.Kilo = d.Kilo;
            danisan.kitleindex = d.kitleindex;
            danisan.vctyag = d.vctyag;
            danisan.kaskütlesi = d.kaskütlesi;
            danisan.DogumTarih = d.DogumTarih;

            c.SaveChanges();
            return RedirectToAction("degerler");

        }

        public ActionResult GelenMesaj()
        {
            var mail = (string)Session["DabisanMailAdresi"];
            var mesajlar = c.Mesajlars.Where(x=> x.kime == mail).ToList();
            var gelensayisi = c.Mesajlars.Count(x => x.kime == mail).ToString();
            ViewBag.d1 = gelensayisi;
            var gönderilen = c.Mesajlars.Count(x => x.kimden == mail).ToString();
            ViewBag.d2 = gönderilen;
            return View(mesajlar);
        }


        public ActionResult Gidenmesajlar()
        {
            var mail = (string)Session["DabisanMailAdresi"];
            var mesajlar = c.Mesajlars.Where(x => x.kimden == mail).ToList();
            var gelensayisi = c.Mesajlars.Count(x => x.kime == mail).ToString();
            ViewBag.d1 = gelensayisi;
            var gönderilen = c.Mesajlars.Count(x => x.kimden == mail).ToString();
            ViewBag.d2 = gönderilen;
            return View(mesajlar);
        }

        public ActionResult MesajDetay(int id)
        {
            var degerler = c.Mesajlars.Where(x => x.mesajid == id).ToList();
            var mail = (string)Session["DabisanMailAdresi"];
            var gelensayisi = c.Mesajlars.Count(x => x.kime == mail).ToString();
            ViewBag.d1 = gelensayisi;
            var gönderilen = c.Mesajlars.Count(x => x.kimden == mail).ToString();
            ViewBag.d2 = gönderilen;
            return View(degerler);
        }
        [HttpGet]
        public ActionResult YeniMesaj()
        {
            var mail = (string)Session["DabisanMailAdresi"];
            var gelensayisi = c.Mesajlars.Count(x => x.kime == mail).ToString();
            ViewBag.d1 = gelensayisi;
            var gönderilen = c.Mesajlars.Count(x => x.kimden == mail).ToString();
            ViewBag.d2 = gönderilen;
            return View();
        }
        [HttpPost]
        public ActionResult YeniMesaj(Mesajlar m)
        {
            var mail = (string)Session["DabisanMailAdresi"];
            m.tarih = DateTime.Parse(DateTime.Now.ToShortDateString());
            m.kimden = mail;
            c.Mesajlars.Add(m);
            c.SaveChanges();

            return View();
        }

        public ActionResult EgzersizBeslenme()
        {
            var mail = (string)Session["DabisanMailAdresi"];
            var danisan = c.Danisanlars.Where(x => x.DabisanMailAdresi == mail).ToList();
            return View(danisan);

        }

    }
}

FitnessWeb/FitnessWeb/Views/DanisanPanel/EgzersizBeslenme.cshtml
@using FitnessWeb.Models.Siniflar
@model List<Danisanlar>
@{
    ViewBag.Title = "EgzersizBeslenme";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}
<th class="accent-dark">Öğünler</th>
<table id="" class="table table-striped table-bordered">
    <thead class="thead-dark">
        <tr>

            <th>Sabah Öğün</th>
            <th>Sabah Öğün-2</th>
            <th>Öğle Öğün</th>




            <th>Ara Öğün</th>
            <th>Akşam Öğün</th>
            <th>Akşam Öğün-2</th>


        </tr>
    </thead>
    @foreach (var a in Model)
    {
        <tr>

            <td>@a.ogun1</td>
            <td>@a.ogun2</td>
            <td>@a.ogun3</td>


            <td>@a.ogun4</td>
            <td>@a.ogun5</td>
            <td>@a.ogun6</td>



        </tr>
    }

    
</table>
<th>Egzersizler</th>
<table id="" class="table table-striped table-bordered">
    <thead class="thead-dark">
        <tr>

            <th>Pazartesi</th>
            <th>Salı</th>
            <th>Çarşamba</th>




            <th>Perşembe</th>
           


        </tr>
    </thead>
    @foreach (var a in Model)
    {
        <tr>

            <td>@a.eg1</td>
            <td>@a.eg2</td>
            <td>@a.eg3</td>


            <td>@a.eg4</td>
          



        </tr>
    }
</table>

FitnessWeb/FitnessWeb/Views/DanisanPanel/GelenMesaj.cshtml
@using FitnessWeb.Models.Siniflar
@model List<Mesajlar>
@{
    ViewBag.Title = "GelenMesaj";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}

<!DOCTYPE html>

<html>

<head>

    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

   

    <!-- Tell the browser to be responsive to screen width -->

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->

    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">

    <!-- Ionicons -->

    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    <!-- icheck bootstrap -->


    <link href="~/AdminLTE-3.0.4/plugins/icheck-bootstrap/icheck-bootstrap.min.css" rel="stylesheet" />
    <!-- Theme style -->

    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">

    <!-- Google Font: Source Sans Pro -->

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

</head>

<body class="hold-transition sidebar-mini">

    <!-- Navbar -->
    <!-- /.navbar -->
    <!-- Main Sidebar Container -->
    <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->

    <section class="content-header">

        <div class="container-fluid">

            <div class="row mb-2">

                <div class="col-sm-6">

                    <h1>Mesajlar</h1>

                </div>

                

            </div>

        </div><!-- /.container-fluid -->

    </section>

    <!-- Main content -->

    <section class="content">

        <div class="row">

            <div class="col-md-3">

                <a href="/DanisanPanel/YeniMesaj/" class="btn btn-primary btn-block mb-3">Yeni Mesaj</a>

                <div class="card">

                    <div class="card-header">

                        <h3 class="card-title">Klasörler</h3>

                        <div class="card-tools">

                            <button type="button" class="btn btn-tool" data-card-widget="collapse">

                                <i class="fas fa-minus"></i>

                            </button>

                        </div>

                    </div>

                    <div class="card-body p-0">

                        <ul class="nav nav-pills flex-column">

                            <li class="nav-item active">

                                <a href="/DanisanPanel/GelenMesaj/" class="nav-link">

                                    <i class="fas fa-inbox"></i> Gelen Kutusu

                                    <span class="badge bg-primary float-right">@ViewBag.d1</span>

                                </a>

                            </li>

                            <li class="nav-item">

                                <a href="/DanisanPanel/Gidenmesajlar/" class="nav-link">

                                    <i class="far fa-envelope"></i> Gönderilenler
                                    <span class="badge bg-success float-right">@ViewBag.d2</span>
                                </a>

                            </li>

                           

                        </ul>

                    </div>

                    <!-- /.card-body -->

                </div>

                <!-- /.card -->

               

                <!-- /.card -->

            </div>

            <!-- /.col -->

            <div class="col-md-9">

                <div class="card card-primary card-outline">

                    <div class="card-header">

                        <h3 class="card-title">Gelen Kutusu</h3>

                     

                        <!-- /.card-tools -->

                    </div>

                    <!-- /.card-header -->

                    <div class="card-body p-0">

                        
                            <!-- /.float-right -->

                        </div>

                        <div class="table-responsive mailbox-messages">

                            <table class="table table-hover table-striped">

                                <tbody>
                                    @foreach(var a in Model) {
                                    <tr>

                                        <td>

                                            <div class="icheck-primary">

                                                <input type="checkbox" value="" id="check1">

                                                <label for="check1"></label>

                                            </div>

                                        </td>

                                        <td class="mailbox-star"><a href="#"><i class="fas fa-star text-warning"></i></a></td>

                                        <td class="mailbox-name"><a href="/DanisanPanel/MesajDetay/@a.mesajid">@a.kimden</a></td>

                                        <td class="mailbox-subject">

                                            <b>@a.konu</b> - @a.icerik.Substring(0, 10).ToString();                                       </td>

                                        <td class="mailbox-attachment"></td>

                                        <td class="mailbox-date">@a.tarih.ToShortDateString()</td>

                                    </tr>



                                    }
                                </tbody>

                            </table>

                            <!-- /.table -->

                        </div>

                        <!-- /.mail-box-messages -->

                    </div>

                    <!-- /.card-body -->

                

                </div>

                <!-- /.card -->

            </div>

            <!-- /.col -->

        </div>

        <!-- /.row -->

    </section>



    <!-- /.content-wrapper -->

    

    <!-- Control Sidebar -->

    <aside class="control-sidebar control-sidebar-dark">

        <!-- Control sidebar content goes here -->

    </aside>

    <!-- /.control-sidebar -->
    <!-- ./wrapper -->
    <!-- jQuery -->

    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>

    <!-- Bootstrap 4 -->

    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- AdminLTE App -->

    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>

    <!-- Page Script -->

    <script>
$(function () {

    //Enable check and uncheck all functionality

    $('.checkbox-toggle').click(function () {

      var clicks = $(this).data('clicks')

      if (clicks) {

        //Uncheck all checkboxes

        $('.mailbox-messages input[type=\'checkbox\']').prop('checked', false)

        $('.checkbox-toggle .far.fa-check-square').removeClass('fa-check-square').addClass('fa-square')

      } else {

        //Check all checkboxes

        $('.mailbox-messages input[type=\'checkbox\']').prop('checked', true)

        $('.checkbox-toggle .far.fa-square').removeClass('fa-square').addClass('fa-check-square')

      }

      $(this).data('clicks', !clicks)

    })



    //Handle starring for glyphicon and font awesome

    $('.mailbox-star').click(function (e) {

      e.preventDefault()

      //detect type

      var $this = $(this).find('a > i')

      var glyph = $this.hasClass('glyphicon')

      var fa    = $this.hasClass('fa')



      //Switch states

      if (glyph) {

        $this.toggleClass('glyphicon-star')

        $this.toggleClass('glyphicon-star-empty')

      }



      if (fa) {

        $this.toggleClass('fa-star')

        $this.toggleClass('fa-star-o')

      }

    })

  })</script>

    <!-- AdminLTE for demo purposes -->

    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>

</body>

</html>

FitnessWeb/FitnessWeb/Views/DanisanPanel/Index.cshtml
@model FitnessWeb.Models.Siniflar.Danisanlar



@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}



<link rel="stylesheet" href="../../plugins/fontawesome-free/css/all.min.css">
<!-- Ionicons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<!-- Theme style -->
<link rel="stylesheet" href="../../dist/css/adminlte.min.css">
<!-- Google Font: Source Sans Pro -->
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">


@using (Html.BeginForm("DanisanBilgiGüncelle", "DanisanPanel", FormMethod.Post))
{
    <div class="container bootstrap snippets bootdey">
        <div class="panel-body inf-content">
            <div class="row">
                <div class="col-md-4">
                    <img alt="" style="width:600px;" title="" class="img-circle img-thumbnail isTooltip" src="@Url.Content(Model.GörselUrl)" data-original-title="Usuario">

                </div>
                <div class="col-md-6">
                    <div class="card card-success">
                        <div class="card-header">
                            <h3 class="card-title">Kişisel Bilgiler</h3>
                        </div>
                    </div>
                    <div class="card card-primary">
                        <div class="table-responsive">
                            <table class="table table-user-information">
                                <tbody>

                                    <tr>
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-user  text-primary"></span>
                                                İsim Soyisim
                                            </strong>
                                        </td>
                                        @Html.HiddenFor(x => x.DanisanId)
                                        <td class="text-primary">
                                            @Html.TextBoxFor(x => x.DanisanIsım, new { @class = "form-control" })
                                        </td>

                                    </tr>
                                    <tr>
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-cloud text-primary"></span>
                                                Mail Adresi
                                            </strong>
                                        </td>
                                        <td class="text-primary">
                                            @Html.TextBoxFor(x => x.DabisanMailAdresi, new { @class = "form-control" })
                                        </td>
                                    </tr>

                                    <tr>
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-bookmark text-primary"></span>
                                                Doğum Tarihi
                                            </strong>
                                        </td>
                                        <td class="text-primary">
                                            @Html.TextBoxFor(x => x.DogumTarih, new { @class = "form-control" })
                                        </td>
                                    </tr>

                                    <tr>
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-bookmark text-primary"></span>
                                                İstenilen Hedef
                                            </strong>
                                        </td>
                                        <td class="text-primary">
                                            @Html.TextBoxFor(x => x.istenen, new { @class = "form-control" })
                                        </td>
                                    </tr>



                                    <tr>
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-envelope text-primary"></span>
                                                Cinsiyet
                                            </strong>
                                        </td>
                                        <td class="text-primary">
                                            @Html.TextBoxFor(x => x.Cinsiyet, new { @class = "form-control" })
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-envelope text-primary"></span>
                                                Telefon Numarası
                                            </strong>
                                        </td>
                                        <td class="text-primary">
                                            @Html.TextBoxFor(x => x.TelefonNo, new { @class = "form-control" })
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <strong>
                                                <span class="glyphicon glyphicon-calendar text-primary"></span>
                                                Şifre
                                            </strong>
                                        </td>
                                        <td class="text-primary">
                                            @Html.TextBoxFor(x => x.DanisanSifre, new { @class = "form-control" })
                                        </td>
                                    </tr>



                                </tbody>

                            </table>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-warning">Güncelle</button>
                        </div>
                    </div>
                </div>
                </div>
    </div>
         </div>


}

FitnessWeb/FitnessWeb/Views/DanisanPanel/Kategoriler.cshtml
@{
    ViewBag.Title = "Kategoriler";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}




@using FitnessWeb.Models.Siniflar;
@model List<Kategori>


<br />

<table id="kategoritbl" class="table table-striped table-bordered">
    <thead class="thead-dark">
        <tr>
            <th>Id</th>
            <th>Kategori</th>
            <th>İşlemler</th>
        </tr>
    </thead>
    @foreach (var a in Model)
    {
<tr>
    <td>@a.KategoriId</td>
    <td>@a.KategoriAd</td>

    <td><a id="btn2" href="/DanisanPanel/kategori1/@a.KategoriId" class="btn btn-success">Antrenörleri Gör</a> </td>
    
</tr>
    }
</table>




<script>


</script>

FitnessWeb/FitnessWeb/Views/DanisanPanel/MesajDetay.cshtml
@using FitnessWeb.Models.Siniflar
@model List<Mesajlar>
@{
    ViewBag.Title = "MesajDetay";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}

<!DOCTYPE html>

<html>

<head>

    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>AdminLTE 3 | Read Mail</title>

    <!-- Tell the browser to be responsive to screen width -->

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->

    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">

    <!-- Ionicons -->

    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    <!-- Theme style -->

    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">

    <!-- Google Font: Source Sans Pro -->

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

</head>

<body>

    <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->

    <section class="content-header">

        <div class="container-fluid">

            <div class="row mb-2">

                <div class="col-sm-6">

                    <h1>Mesaj Detayları</h1>

                </div>

            </div>

        </div><!-- /.container-fluid -->

    </section>

    <!-- Main content -->

    <section class="content">

        <div class="container-fluid">

            <div class="row">

                <div class="col-md-3">

                  

                    <div class="card">

                        <div class="card-header">

                            <h3 class="card-title">Klasörler</h3>

                            <div class="card-tools">

                                <button type="button" class="btn btn-tool" data-card-widget="collapse">

                                    <i class="fas fa-minus"></i>

                                </button>

                            </div>

                        </div>

                        <div class="card-body p-0">

                            <ul class="nav nav-pills flex-column">

                                <li class="nav-item active">

                                    <a href="/DanisanPanel/GelenMesaj/" class="nav-link">

                                        <i class="fas fa-inbox"></i> Gelen Kutusu

                                        <span class="badge bg-primary float-right">@ViewBag.d1</span>

                                    </a>

                                </li>

                                <li class="nav-item">

                                    <a href="/DanisanPanel/Gidenmesajlar/" class="nav-link">

                                        <i class="far fa-envelope"></i> Gönderilenler
                                        <span class="badge bg-succes float-right">@ViewBag.d2</span>
                                    </a>

                                </li>

                             
                            </ul>

                        </div>

                        <!-- /.card-body -->

                    </div>


                    <!-- /.card -->

                  

                    <!-- /.card -->

                </div>

                <!-- /.col -->
                @foreach(var a in Model) {
                <div class="col-md-9">

                    <div class="card card-primary card-outline">

                        <div class="card-header">

                            <h3 class="card-title">Mail Oku</h3>

                            <div class="card-tools">

                                <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Previous"><i class="fas fa-chevron-left"></i></a>

                                <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Next"><i class="fas fa-chevron-right"></i></a>

                            </div>

                        </div>

                        <!-- /.card-header -->

                        <div class="card-body p-0">

                            <div class="mailbox-read-info">

                                <h5>Konu: @a.konu</h5>

                                <h6>

                                    Kimden: @a.kimden

                                    <span class="mailbox-read-time float-right">@a.tarih.ToShortDateString()</span>

                                </h6>

                            </div>

                            <!-- /.mailbox-read-info -->

                          

                            <!-- /.mailbox-controls -->

                            <div class="mailbox-read-message">

                              
                                <p>

                                   @a.icerik
                                    </p>
                                    

                            </div>

                            <!-- /.mailbox-read-message -->

                        </div>

                        <!-- /.card-body -->

                      

                        <!-- /.card-footer -->

                        

                        <!-- /.card-footer -->

                    </div>

                    <!-- /.card -->

                </div>
                }
                <!-- /.col -->

            </div>

            <!-- /.row -->

        </div>

    </section>

    <!-- /.content -->
    <!-- /.content-wrapper -->



    <!-- Control Sidebar -->

    <aside class="control-sidebar control-sidebar-dark">

        <!-- Control sidebar content goes here -->

    </aside>

    <!-- /.control-sidebar -->
  

    <!-- ./wrapper -->
    <!-- jQuery -->

    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>

    <!-- Bootstrap 4 -->

    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- AdminLTE App -->

    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>

    <!-- AdminLTE for demo purposes -->

    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>

</body>

</html>

FitnessWeb/FitnessWeb/Views/DanisanPanel/SifreReset.cshtml
@model FitnessWeb.Models.Siniflar.Danisanlar
@{
    Layout = null;
}

<!DOCTYPE html>


<h1>@ViewBag.uyari</h1>
@using(Html.BeginForm("SifreReset","DanisanPanel",FormMethod.Post))
            {
                <br />
                <br />
                <div class="container">
                    <div class="form-group">
                        <div class="form-group">
                            <input type="text" name="DabisanMailAdresi" placeholder="Email Adresiniz" />

                        </div>
                        <div class="form-group">
                            <input type="submit" value="Şifreyi Sıfırla" class="btn btn-success" />
                        </div>
                        
                    </div>
                </div>
            }

FitnessWeb/FitnessWeb/Views/DanisanPanel/degerler.cshtml
@model FitnessWeb.Models.Siniflar.Danisanlar

@{
    ViewBag.Title = "degerler";
    Layout = "~/Views/Shared/_PanelLayout.cshtml";
}

<br />
@using (Html.BeginForm("degergüncelle", "DanisanPanel", FormMethod.Post))
{
    <table id=" " class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>

                <th>Kilo</th>
                <th>Boy</th>
                <th>Vücut Yağ Oranı</th>
                <th>Kas Kütlesi</th>
                <th>Vücut Kitle İndeksi</th>
                <th>İşlemler</th>


            </tr>
        </thead>

        <tr>
            @Html.HiddenFor(x => x.DanisanId)
            <td> @Html.TextBoxFor(x => x.Kilo, new { @class = "form-control" })</td>
            <td> @Html.TextBoxFor(x => x.boy, new { @class = "form-control" })</td>
            <td> @Html.TextBoxFor(x => x.vctyag, new { @class = "form-control" })</td>
            <td> @Html.TextBoxFor(x => x.kaskütlesi, new { @class = "form-control" })</td>
            <td> @Html.TextBoxFor(x => x.kitleindex, new { @class = "form-control" })</td>





            <td> <button type="submit" class="btn btn-outline-success">Güncelle</button></td>

        </tr>


    </table>



}